arb-dir: lib/l10n/arb
template-arb-file: app_zh.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
#preferred-supported-locales:
#  - en
#  - zh
use-deferred-loading: true
nullable-getter: false