/// Generated by AssetsRefGenerator on 2024/04/17
class Res {
  static const String ic_arrow_right = "assets/images/ic_arrow_right.png";
  static const String nav_back = "assets/images/nav_back.png";
}
